url=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
url1=https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash-lite:generateContent
browser=chrome
geminiAPIKey="API_KEY_HERE"
ai.retry.count=3
ai.retry.delay=2000